#!/bin/bash

# change owner to odroid
chown -R odroid:odroid /home/odroid/.navcoin4

# enable service on boot
systemctl daemon-reload
systemctl enable navcoin

echo
echo
echo "Installation completed"
echo
echo "Start navcoin-core with: systemctl start navcoin"
echo
echo
