#!/bin/bash

# required for dpkg
set -e

# delete config files
rm -f /etc/systemd/system/navcoin.service
rm -f /etc/systemd/system/navcoin-repair.service

# reload systemctl services
systemctl daemon-reload
