#!/bin/bash

# install navcoin.conf
mv /etc/navcoin.conf /home/odroid/.navcoin4/navcoin.conf
chmod 640 /home/odroid/.navcoin4/navcoin.conf

# change owner to odroid
chown -R odroid:odroid /home/odroid/.navcoin4

# enable service on boot
systemctl daemon-reload
systemctl enable navcoin
systemctl start navcoin

echo
echo "navcoin started"
echo
echo "Manage with: systemctl start|stop|restart navcoin"
echo
